### ISSUE TITLE
Couldn't able to Debug from Vs code, /bin/sh: 1: daprd: not found

### ISSUE THREAD

**Issue by jayendranarumugam** [dapr/cli#636]
## Ask your question here

Reference from : https://github.com/dapr/dotnet-sdk/issues/611
I'm trying to debug the `controllersample` from my local vs code , in WSL

This is my Launch.json

```
{

            "name": ".NET Core Launch (web) with Dapr",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "daprd-debug",            
            "program": "${workspaceFolder}/bin/Debug/net5.0/ControllerSample.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "\\\\bNow listening on:\\\\s+(https?://\\\\S+)"
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            },
            "postDebugTask": "daprd-down"
        },
``` 

this is my task

```
        {
            "type": "daprd",
            "label": "daprd-debug",
            "appId": "controller",
            "appPort": 5000,
            "dependsOn" : "build"
        },
        {
            "type": "daprd-down",
            "label": "daprd-down",
            "appId": "controller"
        }
```

But when I run I got like the below

Executing task: dotnet build /mnt/f/dapr/dotnet-sdk/examples/AspNetCore/ControllerSample/ControllerSample.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Dapr.Client -> /mnt/f/dapr/dotnet-sdk/bin/Debug/prod/Dapr.Client/netcoreapp3.1/Dapr.Client.dll
  Dapr.AspNetCore -> /mnt/f/dapr/dotnet-sdk/bin/Debug/prod/Dapr.AspNetCore/netcoreapp3.1/Dapr.AspNetCore.dll
  ControllerSample -> /mnt/f/dapr/dotnet-sdk/bin/Debug/examples/ControllerSample/netcoreapp3.1/ControllerSample.dll

Terminal will be reused by tasks, press any key to close it.

> Executing task: daprd-debug <

> Executing command: daprd --app-id "controller" --app-port "5000" --components-path "/home/jayendran/.dapr/components" --placement-host-address "localhost:50005" <

/bin/sh: 1: daprd: not found

Terminal will be reused by tasks, press any key to close it.

P.S I can able to run the application without having any issue,only debug is not working. Am I missing anything here?

**Comment by tonysneed** [comment]
I get this same error running the VS Code Dapr extension on macOS Big Sur.

**Comment by mukundansundar** [comment]
@jayendranarumugam I can see that this issue has been addressed in VSCode Dapr extension. https://github.com/microsoft/vscode-dapr/issues/139
Can this be closed?

cc @philliphoff

**Comment by jayendranarumugam** [comment]
@mukundansundar / @philliphoff  I did uninstall and installed the latest dapr version and initiated the dapr

```
jayendran@JayPC:/mnt/f/dapr/dotnet-sdk/examples/AspNetCore/ControllerSample$ dapr init
⌛  Making the jump to hyperspace...
←  Downloading binaries and setting up components... 
Dapr runtime installed to /home/jayendran/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
    export PATH=$PATH:/home/jayendran/.dapr/bin
✅  Downloading binaries and setting up components...
✅  Downloaded binaries and completed components set up.
ℹ️  daprd binary has been installed to /home/jayendran/.dapr/bin.
ℹ️  dapr_placement container is running.
ℹ️  dapr_redis container is running.
ℹ️  dapr_zipkin container is running.
ℹ️  Use `docker ps` to check running containers.
✅  Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started
```

But still seeing the 

```
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Dapr.Client -> /mnt/f/dapr/dotnet-sdk/bin/Debug/prod/Dapr.Client/netcoreapp3.1/Dapr.Client.dll
  Dapr.AspNetCore -> /mnt/f/dapr/dotnet-sdk/bin/Debug/prod/Dapr.AspNetCore/netcoreapp3.1/Dapr.AspNetCore.dll
  ControllerSample -> /mnt/f/dapr/dotnet-sdk/bin/Debug/examples/ControllerSample/netcoreapp3.1/ControllerSample.dll

Terminal will be reused by tasks, press any key to close it.

> Executing task: daprd-debug <

> Executing command: daprd --app-id "controller" --app-port "5000" --components-path "/home/jayendran/.dapr/components" --placement-host-address "localhost:50005" <

/bin/sh: 1: daprd: not found

Terminal will be reused by tasks, press any key to close it.
```

Did I miss anything here ?

**Comment by mukundansundar** [comment]
@philliphoff Could you guide on this?

**Comment by spottedmahn** [comment]
w/ PR: https://github.com/microsoft/vscode-dapr/pull/149, we can set the path ourselves

![image](https://user-images.githubusercontent.com/14079228/143526735-700c665c-e15a-4eb7-bcef-9addd5402d76.png)

---

in my case, I was running in a [codespace](https://github.com/features/codespaces) so in a container (pretty neat!) & I fixed my error by finding the path do `daprd`.  

![image](https://user-images.githubusercontent.com/14079228/143526954-9c7132b9-904b-4580-b725-67e0853cbe3d.png)

sidenote: how do I do a relative path from my home dir? 🤔

---

I found it by stumbling and running `dapr init` on an already init'd system & it happened to error out w/ the path 😜

>blah:~/quickstarts$ dapr init
⌛  Making the jump to hyperspace...
ℹ️  Installing runtime version 1.5.0
❌  /home/blah/.dapr/bin/daprd file already exists, please run `dapr uninstall` first before running `dapr init`
